### MATERIAS
GET http://localhost:3000/materias


### CREATE
POST http://localhost:3000/materias
content-type: application/json

{
            "id": 3,
            "materia": "Ingles",
            "submat": "Verbo to Be",
            "tempo": 40,
            "certo": 0,
            "total": 0,
            "meta": 65
}

### UPDATE
PUT http://localhost:3000/materias/2
content-type: application/json

{
    "id": 2,
    "materia": "Matemática",
    "submat": "Cálculo 1",
    "tempo": 90,
    "certo": 68,
    "total": 100,
    "meta": 70
}


### GET MATERIAS
GET http://localhost:3000/materias/3

### DELETE MATERIAS
DELETE http://localhost:3000/materias/3
